let all = 
  [ "1",  "Athanor" ;
    "2",  "Mynari" ;
    "3",  "Erenheim" ;
    "4",  "Sans-Visage" ;
    "5",  "Didalane" ;
    "6",  "Cauchemars" ;
    "7",  "Aphorismes" ;
    "8",  "Le Soiffard" ;
    "9",  "Apocalypse" ;
    "10", "Théologie" ;
    "11", "Serrig" ;
    "12", "Nomination" ;
    "13", "Arkadir" ; 
    "14", "Haute Trahison" ;
    "15", "Ordo Eborius" ;
    "16", "Suidaster" ;
    "17", "Mémoire" ;
    "18", "Hans Banach" ;
    "19", "Simmera" ;
    "20", "Geerart" ;
    "21", "Guirevennec" ;
    "22", "Invasion" ;
    "23", "Archange" ;
    "24", "Josephus" ;
    "25", "Parchaki" ;
    "26", "Récompense" ;
    "27", "Généalogie" ;
    "28", "Prédécesseur" ;
    "29", "Informateur" ;
    "30", "Croisière" ;
    "31", "Patriarche" ;
    "32", "Le&nbsp;Poison" ;
    "33", "Nature&nbsp;Divine" ;
    "34", "Lucrèce" ;
  ]
